package KieRule;

import com.example.drools.model.Order;

rule "HDFC"
	when
		orderObject : Order(cardType == "HDFC" && price > 	10000);
	then
		orderObject.setDiscount(10);
		orderObject.setMonto(orderObject.getPrice()-orderObject.getPrice()*orderObject.getDiscount()/100);
end

rule "ICICI"
	when
		orderObject : Order(cardType == "ICICI" && price > 	15000);
	then
		orderObject.setDiscount(8);
end

rule "DBS"
	when
		orderObject : Order(cardType == "DBS" && price > 	15000);
	then
		orderObject.setDiscount(15);
end
		